from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup


how_many_k = InlineKeyboardMarkup(row_width=5)
but_1 = InlineKeyboardButton(text='1', callback_data='1')
but_2 = InlineKeyboardButton(text='2', callback_data='2')
but_3 = InlineKeyboardButton(text='3', callback_data='3')
but_4 = InlineKeyboardButton(text='4', callback_data='4')
but_5 = InlineKeyboardButton(text='5', callback_data='5')
how_many_k.add(but_1, but_2, but_3, but_4, but_5)

pick_h_ikb = InlineKeyboardMarkup()
b_tusk = InlineKeyboardButton(text="Tusk", callback_data="Tusk")
b_mirana = InlineKeyboardButton(text="Mirana", callback_data="Mirana")
b_rubick = InlineKeyboardButton(text="Rubick", callback_data="Rubick")
b_tiny = InlineKeyboardButton(text="Tiny", callback_data="Tiny")
b_primalbeast = InlineKeyboardButton(text="Primal Beast", callback_data="Primal Beast")
b_crystalmaiden = InlineKeyboardButton(text="C.M.", callback_data="Crystal Maiden")
b_treantprotector = InlineKeyboardButton(text="Treant", callback_data="Treant Protector")
b_razor = InlineKeyboardButton(text="Razor", callback_data="Razor")
b_pangolier = InlineKeyboardButton(text="Pangolier", callback_data="Pangolier")
b_shadowfiend = InlineKeyboardButton(text="S.F.", callback_data="Shadow Fiend")
b_leshrac = InlineKeyboardButton(text="Leshrac", callback_data="Leshrac")
b_ursa = InlineKeyboardButton(text="Ursa", callback_data="Ursa")
b_facelessvoid = InlineKeyboardButton(text="Faceless Void", callback_data="Faceless Void")
b_silencer = InlineKeyboardButton(text="Silencer", callback_data="Silencer")
b_pudge = InlineKeyboardButton(text="Pudge", callback_data="Pudge")
b_lina = InlineKeyboardButton(text="Lina", callback_data="Lina")
b_doom = InlineKeyboardButton(text="Doom", callback_data="Doom")
b_riki = InlineKeyboardButton(text="Riki", callback_data="Riki")
b_hoodwink = InlineKeyboardButton(text="Hoodwink", callback_data="Hoodwink")
b_drowranger = InlineKeyboardButton(text="Drow Ranger", callback_data="Drow Ranger")
b_morphling = InlineKeyboardButton(text="Morph", callback_data="Morphling")
b_emberspirit = InlineKeyboardButton(text="Ember Spirit", callback_data="Ember Spirit")
b_dawnbreaker = InlineKeyboardButton(text="Dawnbreaker", callback_data="Dawnbreaker")
b_marci = InlineKeyboardButton(text="Marci", callback_data="Marci")
b_snapfire = InlineKeyboardButton(text="Snapfire", callback_data="Snapfire")
b_monkeyking = InlineKeyboardButton(text="M.K.", callback_data="Monkey King")
b_mars = InlineKeyboardButton(text="Mars", callback_data="Mars")
b_sniper = InlineKeyboardButton(text="Sniper", callback_data="Sniper")
b_zeus = InlineKeyboardButton(text="Zeus", callback_data="Zeus")
b_legioncommander = InlineKeyboardButton(text="L.C.", callback_data="Legion Commander")
b_nagasiren = InlineKeyboardButton(text="Naga Siren", callback_data="Naga Siren")
b_bloodseeker = InlineKeyboardButton(text="Bloodseeker", callback_data="Bloodseeker")
b_bountyhunter = InlineKeyboardButton(text="B.H.", callback_data="Bounty Hunter")
b_skywrathmage = InlineKeyboardButton(text="Skywrath", callback_data="Skywrath Mage")
b_undying = InlineKeyboardButton(text="Undying", callback_data="Undying")
b_earthshaker = InlineKeyboardButton(text="Earthshaker", callback_data="Earthshaker")
b_broodmother = InlineKeyboardButton(text="Broodmother", callback_data="Broodmother")
b_magnus = InlineKeyboardButton(text="Magnus", callback_data="Magnus")
b_invoker = InlineKeyboardButton(text="Invoker", callback_data="Invoker")
b_jakiro = InlineKeyboardButton(text="Jakiro", callback_data="Jakiro")
b_spiritbreaker = InlineKeyboardButton(text="Spirit Breaker", callback_data="Spirit Breaker")
b_clockwerk = InlineKeyboardButton(text="Clockwerk", callback_data="Clockwerk")
b_lifestealer = InlineKeyboardButton(text="Lifestealer", callback_data="Lifestealer")
b_windranger = InlineKeyboardButton(text="WR", callback_data="Windranger")
b_lycan = InlineKeyboardButton(text="Lycan", callback_data="Lycan")
b_batrider = InlineKeyboardButton(text="Batrider", callback_data="Batrider")
b_naturesprophet = InlineKeyboardButton(text="Nature's Prophet", callback_data="Nature's Prophet")
b_nyxassassin = InlineKeyboardButton(text="Nyx Assassin", callback_data="Nyx Assassin")
b_disruptor = InlineKeyboardButton(text="Disruptor", callback_data="Disruptor")
b_viper = InlineKeyboardButton(text="Viper", callback_data="Viper")
b_beastmaster = InlineKeyboardButton(text="Beastmaster", callback_data="Beastmaster")
b_sven = InlineKeyboardButton(text="Sven", callback_data="Sven")
b_deathprophet = InlineKeyboardButton(text="D.P.", callback_data="Death Prophet")
b_queenofpain = InlineKeyboardButton(text="Q.P.", callback_data="Queen of Pain")
b_enchantress = InlineKeyboardButton(text="Enchantress", callback_data="Enchantress")
b_weaver = InlineKeyboardButton(text="Weaver", callback_data="Weaver")
b_huskar = InlineKeyboardButton(text="Huskar", callback_data="Huskar")
b_tinker = InlineKeyboardButton(text="Tinker", callback_data="Tinker")
b_lich = InlineKeyboardButton(text="Lich", callback_data="Lich")
b_puck = InlineKeyboardButton(text="Puck", callback_data="Puck")
b_timbersaw = InlineKeyboardButton(text="Timbersaw", callback_data="Timbersaw")
b_earthspirit = InlineKeyboardButton(text="Earth Spirit", callback_data="Earth Spirit")
b_witchdoctor = InlineKeyboardButton(text="Witch Doctor", callback_data="Witch Doctor")
b_venomancer = InlineKeyboardButton(text="Venomancer", callback_data="Venomancer")
b_dazzle = InlineKeyboardButton(text="Dazzle", callback_data="Dazzle")
b_darkwillow = InlineKeyboardButton(text="Dark Willow", callback_data="Dark Willow")
b_outworlddestroyer = InlineKeyboardButton(text="O.D.", callback_data="Outworld Destroyer")
b_tidehunter = InlineKeyboardButton(text="Tidehunter", callback_data="Tidehunter")
b_phoenix = InlineKeyboardButton(text="Phoenix", callback_data="Phoenix")
b_techies = InlineKeyboardButton(text="Techies", callback_data="Techies")
b_antimage = InlineKeyboardButton(text="Anti-Mage", callback_data="Anti-Mage")
b_enigma = InlineKeyboardButton(text="Enigma", callback_data="Enigma")
b_ogremagi = InlineKeyboardButton(text="Ogre Magi", callback_data="Ogre Magi")
b_gyrocopter = InlineKeyboardButton(text="Gyrocopter", callback_data="Gyrocopter")
b_templarassassin = InlineKeyboardButton(text="Templar Assassin", callback_data="Templar Assassin")
b_bane = InlineKeyboardButton(text="Bane", callback_data="Bane")
b_voidspirit = InlineKeyboardButton(text="Void Spirit", callback_data="Void Spirit")
b_winterwyvern = InlineKeyboardButton(text="Winter Wyvern", callback_data="Winter Wyvern")
b_darkseer = InlineKeyboardButton(text="Dark Seer", callback_data="Dark Seer")
b_stormspirit = InlineKeyboardButton(text="Storm Spirit", callback_data="Storm Spirit")
b_visage = InlineKeyboardButton(text="Visage", callback_data="Visage")
b_lion = InlineKeyboardButton(text="Lion", callback_data="Lion")
b_io = InlineKeyboardButton(text="Io", callback_data="Io")
b_juggernaut = InlineKeyboardButton(text="Juggernaut", callback_data="Juggernaut")
b_terrorblade = InlineKeyboardButton(text="Terrorblade", callback_data="Terrorblade")
b_lonedruid = InlineKeyboardButton(text="Lone Druid", callback_data="Lone Druid")
b_kunkka = InlineKeyboardButton(text="Kunkka", callback_data="Kunkka")
b_grimstroke = InlineKeyboardButton(text="Grimstroke", callback_data="Grimstroke")
b_chaosknight = InlineKeyboardButton(text="C.K.", callback_data="Chaos Knight")
b_clinkz = InlineKeyboardButton(text="Clinkz", callback_data="Clinkz")
b_slardar = InlineKeyboardButton(text="Slardar", callback_data="Slardar")
b_pugna = InlineKeyboardButton(text="Pugna", callback_data="Pugna")
b_arcwarden = InlineKeyboardButton(text="Arc Warden", callback_data="Arc Warden")
b_necrophos = InlineKeyboardButton(text="Necrophos", callback_data="Necrophos")
b_nightstalker = InlineKeyboardButton(text="Night Stalker", callback_data="Night Stalker")
b_vengefulspirit = InlineKeyboardButton(text="Vengeful Spirit", callback_data="Vengeful Spirit")
b_alchemist = InlineKeyboardButton(text="Alchemist", callback_data="Alchemist")
b_phantomlancer = InlineKeyboardButton(text="P.L.", callback_data="Phantom Lancer")
b_phantomassassin = InlineKeyboardButton(text="Phantom Assassin", callback_data="Phantom Assassin")
b_abaddon = InlineKeyboardButton(text="Abaddon", callback_data="Abaddon")
b_axe = InlineKeyboardButton(text="Axe", callback_data="Axe")
b_keeperofthelight = InlineKeyboardButton(text="Kotl", callback_data="Keeper of the Light")
b_dragonknight = InlineKeyboardButton(text="D.K", callback_data="Dragon Knight")
b_omniknight = InlineKeyboardButton(text="Omniknight", callback_data="Omniknight")
b_shadowshaman = InlineKeyboardButton(text="Shadow Shaman", callback_data="Shadow Shaman")
b_spectre = InlineKeyboardButton(text="Spectre", callback_data="Spectre")
b_wraithking = InlineKeyboardButton(text="W.K.", callback_data="Wraith King")
b_ancientapparition = InlineKeyboardButton(text="Ancient Apparition", callback_data="Ancient Apparition")
b_shadowdemon = InlineKeyboardButton(text="Shadow Demon", callback_data="Shadow Demon")
b_brewmaster = InlineKeyboardButton(text="Brewmaster", callback_data="Brewmaster")
b_sandking = InlineKeyboardButton(text="Sand King", callback_data="Sand King")
b_warlock = InlineKeyboardButton(text="Warlock", callback_data="Warlock")
b_oracle = InlineKeyboardButton(text="Oracle", callback_data="Oracle")
b_luna = InlineKeyboardButton(text="Luna", callback_data="Luna")
b_trollwarlord = InlineKeyboardButton(text="Troll", callback_data="Troll Warlord")
b_centaurwarrunner = InlineKeyboardButton(text="Centaur", callback_data="Centaur Warrunner")
b_chen = InlineKeyboardButton(text="Chen", callback_data="Chen")
b_bristleback = InlineKeyboardButton(text="Bristleback", callback_data="Bristleback")
b_eldertitan = InlineKeyboardButton(text="Elder Titan", callback_data="Elder Titan")
b_underlord = InlineKeyboardButton(text="Underlord", callback_data="Underlord")
b_medusa = InlineKeyboardButton(text="Medusa", callback_data="Medusa")
b_meepo = InlineKeyboardButton(text="Meepo", callback_data="Meepo")
b_slark = InlineKeyboardButton(text="Slark", callback_data="Slark")
pick_h_ikb.add(b_tusk, b_mirana, b_rubick, b_tiny, b_primalbeast, b_crystalmaiden,
               b_treantprotector, b_razor, b_pangolier, b_shadowfiend, b_leshrac, b_ursa, b_facelessvoid, b_silencer,
               b_pudge, b_lina, b_doom, b_riki, b_hoodwink, b_drowranger, b_morphling, b_emberspirit, b_dawnbreaker,
               b_marci, b_snapfire, b_monkeyking, b_mars, b_sniper, b_zeus, b_legioncommander, b_nagasiren,
               b_bloodseeker,
               b_bountyhunter, b_skywrathmage, b_undying, b_earthshaker, b_broodmother, b_magnus, b_invoker, b_jakiro,
               b_spiritbreaker, b_clockwerk, b_lifestealer, b_windranger, b_lycan, b_batrider,
               b_naturesprophet, b_nyxassassin, b_disruptor, b_viper, b_beastmaster, b_sven, b_deathprophet,
               b_queenofpain,
               b_enchantress, b_weaver, b_huskar, b_tinker, b_lich, b_puck, b_timbersaw, b_earthspirit, b_witchdoctor,
               b_venomancer, b_dazzle, b_darkwillow, b_outworlddestroyer, b_tidehunter, b_phoenix, b_techies,
               b_antimage,
               b_enigma, b_ogremagi, b_gyrocopter, b_templarassassin, b_bane, b_voidspirit, b_winterwyvern, b_darkseer,
               b_stormspirit, b_visage, b_lion, b_io, b_juggernaut, b_terrorblade, b_lonedruid, b_kunkka, b_grimstroke,
               b_chaosknight, b_clinkz, b_slardar, b_pugna, b_arcwarden, b_necrophos, b_nightstalker, b_vengefulspirit,
               b_alchemist, b_phantomlancer, b_phantomassassin, b_abaddon, b_axe, b_keeperofthelight,
               b_dragonknight, b_omniknight, b_shadowshaman, b_spectre, b_wraithking, b_ancientapparition,
               b_shadowdemon,
               b_brewmaster, b_sandking, b_warlock, b_oracle, b_luna, b_trollwarlord, b_centaurwarrunner, b_chen,
               b_bristleback, b_eldertitan, b_underlord, b_medusa, b_meepo, b_slark, )
