name: Push to Docker Registry

on:
  push:
    branches: [ "master" ]

jobs:
  push-to-docker-registry:
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag dotaheroes:latest

      - name: Push to Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/dotaheroes/dotaheroes:latest
