name: Push to Docker Registry

on:
  push:
    branches: [ "master" ]

jobs:
  push-to-docker-registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: ruff
      run: |
       ruff . --no-cache
    - name: mypy
      run: |
       mypy --strict --cache-dir=/dev/null .
    - name: pytest tests
      run: |
        pytest
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag dotaheroes:latest
    - name: Push to Docker Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/dotaheroes/dotaheroes:latest
